version: '2'
services:
  # Our frontstage machine which is responsible for delivering the correct Electronic Questionarie (EQ)
  ras-frontstage:
    build:
      #context: git@github.com:ONSdigital/ras-frontstage.git
      context: ras-frontstage
    ports:
      - "5101:5001"
    networks:
      - ras

  ras-party:
    build:
      #context: git@github.com:ONSdigital/ras-party.git
      context: ras-party
    ports:
      - "5162:5062"
    networks:
      - ras

  django-oauth2-test:
    build:
      context: django-oauth2-test
    ports:
      - "8040:8040"
    networks:
      - ras

  ras-collection-instrument:
    build:
      context: ras-collection-instrument
    ports:
      - "5152:5052"
    environment:
      - spring.datasource.url=jdbc:postgresql://postgres:5432/postgres
      - eureka.client.serviceUrl.defaultZone=http://ras-registry:8761/eureka/
    networks:
      - ras



  # Spring config server - not currently used.
  #ras-config:
  #  build:
  #    context: ras-config
  #  environment:
  #    - server.port=8080
  #  networks:
  #    - ras

  # Database container:
  # The defaut port to postgres DB is 5432. However some people have postgres running on their local machine, so we
  # need to change our external port number to map our local port to the docker instance port. We are using 5431 until
  # we here otherwise
  postgres:
    image: postgres:9.6
    ports:
      - "5431:5432"
    networks:
      - ras

networks:
  ras:
