version: '2'
services:
  ras-frontstage:
    build:
      context: https://github.com/ONSdigital/ras-frontstage.git
    ports:
      - "5000:5000"
    networks:
      - ras
  ras-respondent:
    build: 
      context: ras-respondent
    environment:
      - eureka.client.serviceUrl.defaultZone=http://ras-registry:8761/eureka/
    networks:
      - ras
  ras-gateway:
    build: 
      context: ras-gateway
    environment:
      - eureka.client.serviceUrl.defaultZone=http://ras-registry:8761/eureka/
    ports:
      - "8080:8080"
    networks:
      - ras
  ras-authentication:
    build: 
      context: ras-authentication
    ports:
      - "8888:8080"
    # volumes:
    #  - "~/.gradle:/root/.gradle"
    # environment:
    #  - CLOUD_FOUNDRY_CONFIG_PATH=/ras-config
    networks:
      - ras
  ras-registry:
    build: 
      context: ras-registry
    networks:
      - ras
  ras-config:
    build: 
      context: ras-config
    networks:
      - ras

networks:
  ras:
