version: '2'
services:
  ras-frontstage:
    build:
      context: https://github.com/ONSdigital/ras-frontstage.git
    ports:
      - "5000:5000"
    networks:
      - ras
  ras-respondent:
    build: 
      context: ras-respondent
    networks:
      - ras
  ras-gateway:
    build: 
      context: ras-gateway
    ports:
      - "8080:8080"
    networks:
      - ras
  ras-authentication:
    build: 
      context: ras-authentication
    networks:
      - ras
  ras-registry:
    build: 
      context: ras-registry
    networks:
      - ras
  ras-config:
    build: 
      context: ras-config
    networks:
      - ras

networks:
  ras:
