version: '2'
services:
  ras-frontstage:
    build:
      context: https://github.com/ONSdigital/ras-frontstage.git
    ports:
      - "5000:5000"
    networks:
      - ras
  ras-respondent:
    build: 
      context: ras-respondent
    environment:
      - server.port=8080
      - eureka.client.serviceUrl.defaultZone=http://ras-registry:8761/eureka/
    networks:
      - ras
  ras-gateway:
    build: 
      context: ras-gateway
    ports:
      - "8080:8080"
    environment:
      - server.port=8080
      - eureka.client.serviceUrl.defaultZone=http://ras-registry:8761/eureka/
    networks:
      - ras
  ras-authentication:
    build: 
      context: ras-authentication
    ports:
      - "8888:8080"
    environment:
      - server.port=8080
      - CLOUD_FOUNDRY_CONFIG_PATH=/ras-config
    networks:
      - ras
  ras-registry:
    build: 
      context: ras-registry
    environment:
      - server.port=8080
    networks:
      - ras
  ras-config:
    build: 
      context: ras-config
    environment: 
      - server.port=8080
    networks:
      - ras

networks:
  ras:
